name: Generate Snake

on:
  schedule:
    # Her 6 saatte bir otomatik çalışır
    - cron: "0 */6 * * *"
  workflow_dispatch:

# Bota yazma izni veren sihirli satırlar (Hata almaman için şart)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Depoyu kontrol eder
      - uses: actions/checkout@v3

      # Yılan animasyonunu senin istediğin okyanus renkleriyle üretir
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

      # Üretilen dosyaları 'output' dalına (branch) yükler
      - uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
